### PR TITLE
give fetchManifest and fetchCircle their own hooks

### PR DESCRIPTION
**Pull request by levity**
## Motivation and Context

just removing a grouping that is no longer relevant

### CODE REVIEW

**Comment by levity** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2079** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2079" target="_blank">Graphite</a> 
    * **PR #2080** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2080" target="_blank">Graphite</a>  👈
      * **PR #2081** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2081" target="_blank">Graphite</a> 
        * **PR #2082** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2082" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2080?utm_source=stack-comment).

**Review by crabsinger — APPROVED** [review]

**Comment by levity** [comment]
[Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2080) couldn't merge this PR because it failed optional checks and "ignore optional checks" was not selected.

**Comment by levity** [comment]
@levity queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2080).

**Comment by levity** [comment]
@levity merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2080).

**Pull request merged**
