### PR TITLE
Improve User profile picture upload pattern

### LINKED ISSUE #1496: Improve User profile picture upload pattern
### What's happening:
Uploading images is a difficult user flow
### What should be happening
Uploading images should follow the add Org image process flow

1.  Button to upload new Image
Image
2. Auto-save Image after selected 
Image
3. Error state
- If image too large return error : The maximum image size is 3mb, please try again with a smaller file.
4. While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."

### PR DESCRIPTION
**Pull request by sshmm**
## Motivation and Context
resolves #1496

## Description
Update AvatarUpload.tsx to follow org logo upload in OrganizationSettingsPage.tsx
- Button to upload new Image
- Auto-save Image after selected
- Error state
- While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."

Update updateProfileAvatar mutation to return the avatar to display after upload

#### Note:
I kept the same way of fetching the data by recoil. I think it needs a separate issue because there will be many changes in profile page

## Test and Deployment Plan
1- Go to your profile page
2- click edit profile
3- use correct image format to check the uploaded avatar
4- use large size photo or wrong format to check the error message

## Screenshots (if appropriate):
image

image

### CODE REVIEW

**Comment by crabsinger** [comment]
@sshmm the "Saving" modal seems to behave weirdly. I see it show when the mutation is saving the updated path for the users profile, but NOT during the file upload itself.

**Review by crabsinger — APPROVED** [review]
@sshmm looking good. Would be nice if we can make the saving indcator show while the file is being uploaded, but may be hard with teh way this form is constructed. Take a look, and if its too much work, lets ignore it for now and we'll fix that when we do a full rewrite of the profile page.

I pushed a few new commits, including a formatBytes helper function that shows a pretty value for the max file size limits.

**Comment by crabsinger** [comment]
@sshmm actually I didn't push the commits to your branch: but pushed them over to here: https://github.com/coordinape/coordinape/compare/main...Improve_User_profile_picture_upload_pattern

can you pull those latest 3 commits into this PR, fix the failing test, and look into the saving issue, and then should be ready for merge. 🙏

**Comment by sshmm** [comment]
> @sshmm actually I didn't push the commits to your branch: but pushed them over to here: [main...Improve_User_profile_picture_upload_pattern](https://github.com/coordinape/coordinape/compare/main...Improve_User_profile_picture_upload_pattern)
> 
> can you pull those latest 3 commits into this PR, fix the failing test, and look into the saving issue, and then should be ready for merge. 🙏



> @sshmm looking good. Would be nice if we can make the saving indcator show while the file is being uploaded, but may be hard with teh way this form is constructed. Take a look, and if its too much work, lets ignore it for now and we'll fix that when we do a full rewrite of the profile page.
> 
> I pushed a few new commits, including a formatBytes helper function that shows a pretty value for the max file size limits.

I will check it and update it tonight if possible

**Pull request merged**
