### PR TITLE
pricePerShare in Hasura

### PR DESCRIPTION
**Pull request by levity**
## Motivation and Context

With Yearn vaults, we often have to calculate `pricePerShare` to convert between wrapped and unwrapped amounts. When all other data comes through Hasura, having to make additional async requests to fetch data from an Ethereum provider is unwieldy ([e.g.](https://github.com/coordinape/coordinape/blob/main/src/pages/DistributionsPage/queries.ts#L122)). Ideally it would all happen through Hasura.

## Description

This PR:
- adds a new serverless function that stands up a tiny GraphQL server whose only query operation is a way of calculating pricePerShare
- adds the remote schema to Hasura config
- adds a remote relationship in Hasura between `vaults` and `price_per_share`

## Test and Deployment Plan

- [x] deploy to staging to verify that Hasura still works 
- [x] run a test GraphQL query, e.g.:
```
{
  organizations_by_pk(id: [id of some org with vaults]) {
    vaults {
      id
      symbol
      token_address
      price_per_share
    }
  }
}
```

## Notes

There's lots of room for performance improvement via caching. And maybe we'll decide that this particular use case isn't so important, but at least now we have example code for setting up a remote schema.
- I found myself wishing we already had a monorepo to keep dependencies separate. I had to work with Apollo Server v3, because v4 (just released) uses newer Typescript features, which confuses our linter.

### CODE REVIEW

**Review by zashton — DISMISSED** [review]
image

remote schema works for me,
but had to click on reload to make the hasura metadata consistent
hasura also has built in response caching that we can use here
https://hasura.io/docs/latest/queries/response-caching/

**Comment by levity** [comment]
Welp, deployed to staging, and I'm seeing an issue that I didn't see on dev, possibly because the Hasura version numbers are different between the two environments.

Screen Shot 2022-10-22 at 3 36 49 PM

**Comment by levity** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1520** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1520" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1520?utm_source=stack-comment).

**Comment by crabsinger** [comment]
> Welp, deployed to staging, and I'm seeing an issue that I didn't see on dev, possibly because the Hasura version numbers are different between the two environments.

Yeah, so maybe we need to figure out and resolve https://github.com/coordinape/coordinape/pull/1429/files before this goes ahead.

**Comment by CryptoGraffe** [comment]
The hasura upgrade is done so maybe this can be retested now?

**Comment by levity** [comment]
> The hasura upgrade is done so maybe this can be retested now?

Still running into issues; it appears unrelated to the Hasura version after all. I split out just the API handler into #1624 so I can deploy it first for further diagnosis. This PR now contains only the Hasura metadata changes to add the remote schema and relationship.

**Comment by levity** [comment]
Merged this one back down into #1624 so it deploys all at once

**Pull request closed without merging**
