### PR TITLE
this is the fix for the mobile ui problem

### PR DESCRIPTION
**Pull request by yahiamarzouk**
## Motivation and Context

this fixes the mobile UI problem when on circle page edit screen

## Screenshots (if appropriate):

Screen Shot 2022-08-16 at 5 51 47 PM

## Related Issue

 
https://github.com/coordinape/coordinape/issues/1137

### CODE REVIEW

**Comment by crabsinger** [comment]
@reeserj can you try to retest this and confirm it fixes the issue - im not sure if i can reproduce the issue that's exactly happening.

**Comment by reeserj** [comment]
Looks good to me!

**Review by crabsinger — APPROVED** [review]

**Comment by crabsinger** [comment]
Thanks for the PR @yahiamarzouk !

**Comment by yahiamarzouk** [comment]
> Thanks for the PR @yahiamarzouk !

Hope i can contribute more

**Pull request merged**
