### PR TITLE
App UI Icons

### PR DESCRIPTION
**Pull request by smombartz**
Created figma folder with App UI icons. As per conversation with Graffe.

### CODE REVIEW

**Review by CryptoGraffe — CHANGES_REQUESTED** [review]
@smombartz Can you drop the extra `icon` nested folder and also name these consistently, e.g. `WalletConnect` is capitalized and `coinbase wallet` has a space in it whereas other ones are lowercase and use dashes for multi-word. `discrod` is misspelled.

**Comment by CryptoGraffe** [comment]
Thanks for doing this, it's gonna be great when we get it all hooked up

**Comment by CryptoGraffe** [comment]
> @smombartz Can you drop the extra `icon` nested folder and also name these consistently, e.g. `WalletConnect` is capitalized and `coinbase wallet` has a space in it whereas other ones are lowercase and use dashes for multi-word. `discrod` is misspelled.

FWIW I'm asking for this now because I'm assuming these names are in Figma and it would be great to get it right now instead of accidentally reintroduce diff names later

**Comment by smombartz** [comment]
> > @smombartz Can you drop the extra `icon` nested folder and also name these consistently, e.g. `WalletConnect` is capitalized and `coinbase wallet` has a space in it whereas other ones are lowercase and use dashes for multi-word. `discrod` is misspelled.
> 
> FWIW I'm asking for this now because I'm assuming these names are in Figma and it would be great to get it right now instead of accidentally reintroduce diff names later

totally! good catch. i was moving fast and we definitely want them to be consistent!!

**Comment by smombartz** [comment]
@CryptoGraffe made the requested changes. should all be nice and tidy now.

**Review by CryptoGraffe — APPROVED** [review]

**Pull request merged**
