### PR TITLE
Fixup/members page UI

### PR DESCRIPTION
**Pull request by wingfeatherwave**
Screen Shot 2022-09-28 at 10 34 59 AM

- only show nominee table if there are nominees
- change x color to neutral
- minor ui spacing updates
- button name fix: manager member to manage member
- admin link in circle page circle should go to settings not member page
- add members link to circle hover links
Screen Shot 2022-09-28 at 10 39 49 AM

### CODE REVIEW

**Review by crabsinger — APPROVED** [review]

**Comment by crabsinger** [comment]
Doesn't seem to offer a non-admin option to Nominate someone ?

**Comment by wingfeatherwave** [comment]
> Doesn't seem to offer a non-admin option to Nominate someone ?

I merged before I saw this comment.  I'll look at that tomorrow

**Comment by wingfeatherwave** [comment]
> Doesn't seem to offer a non-admin option to Nominate someone ?

@crabsinger It seems to be working properly, and that non-admin can indeed nominate.  Can you point me to where you weren't seeing it?

Screen Shot 2022-09-29 at 11 20 09 AM

**Comment by crabsinger** [comment]
@wingfeatherwave nevermind - it was on a circle with Vouching disabled...

**Pull request merged**
