### PR TITLE
remove DefaultPage

### PR DESCRIPTION
**Pull request by levity**
## Motivation and Context

It is no longer reachable, since we create a sample DAO for each new user

### CODE REVIEW

**Comment by levity** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2086** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2086" target="_blank">Graphite</a> 
    * **PR #2087** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2087" target="_blank">Graphite</a> 
      * **PR #2089** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2089" target="_blank">Graphite</a> 
        * **PR #2090** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2090" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2090?utm_source=stack-comment).

**Comment by levity** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2086** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2086" target="_blank">Graphite</a> 
    * **PR #2087** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2087" target="_blank">Graphite</a> 
      * **PR #2089** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2089" target="_blank">Graphite</a> 
        * **PR #2090** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/2090" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2090?utm_source=stack-comment).

**Review by crabsinger — DISMISSED** [review]

**Comment by levity** [comment]
@levity queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2090).

**Comment by levity** [comment]
[Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2090) rebased this pull request as part of a merge.

**Pull request merged**
