### PR TITLE
new GIVE page

### LINKED ISSUE #830: Autosave allocations
**Summary:**

Autosave changes on the allocations page directly to server.

**Details:**

Currently, on the Allocate page (https://app.coordinape.com/allocation) whenever you make a change to `notes` or `GIVE` the changes are queued up and a "Save Allocations" button appears when there are unsaved changes.
Screen Shot 2022-04-25 at 5 00 56 PM

See https://github.com/coordinape/coordinape/blob/c12f9c67324b2b6f00abd6347a916e1803652a1a/src/pages/AllocationPage/AllocationPage.tsx#L214

This issue is to change the functionality from queueing up all changes under the 'Save Allocations' button, to immediately making the changes against the server.

This is like switching from an old Microsoft Word model of needing to click "Save", to a Google Docs ux of autosaving.

**Notes:**
- we don't want to make too many requests to the server, so we should still queue up changes and send them every 1-5 seconds, if someone is typing into their notes.

**Design:**
Continue to show the "Save Allocation" button when changes are queued up but not yet sent to the server. Once the changes have been sent to the server, change the button to green and have it say "Allocations Saved".

### LINKED ISSUE #925: 1.5.3- Create new row / list components for user allocation table
[1.5.3 Allocation Updates Notion](https://www.notion.so/coordinape/1-5-Allocations-Updates-21274b560fd74d1d9c9f99fda6dbe636) ||| [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5149%3A19125)

- First row is for the logged in user, allow opting in/out of receiving GIVE
- Arrow Icons  in the middle need to correspond to the the Opt-in/opt-out status [Arrow detail ](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=6408%3A27703)
- Avatar and name on left, 
- Yellow tag on the row if member is a collaborator
- Show icon if user already wrote a note for that member

### LINKED ISSUE #926: 1.5.3- Create component for “detail view” on a contributor
[1.5.3 Allocation Updates Notion](https://www.notion.so/coordinape/1-5-Allocations-Updates-21274b560fd74d1d9c9f99fda6dbe636) ||| [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5149%3A19135)

- list of contributions with collapsing rows
- “leave a note”
- Header with avatar, name, and social links
- Right hand column “Next” and “Previous” buttons paginate contributions for selected user.
- When row for a given user is selected, create "Add to Collaborators" button on row (Used to be “Select teammates”)

### LINKED ISSUE #927: 1.5.3- Create Allocation Filterbar component
[1.5.3 Allocation Updates Notion](https://www.notion.so/coordinape/1-5-Allocations-Updates-21274b560fd74d1d9c9f99fda6dbe636) ||| [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5149%3A19125)

- Show remaining give
- “Distribute Evenly” button
- Member search field
- Tag filter selector
- “Collaborators/Members” toggle
- Tag Filter should use a Dropdown multiselect “**Multiple Selection”**  that works as the following or similarly to “Multiple search selection” on [https://semantic-ui.com/modules/dropdown.html](https://semantic-ui.com/modules/dropdown.html)

### LINKED ISSUE #928: 1.5.3- Assemble all the above components into the complete “Allocate” page
[1.5.3 Allocation Updates Notion](https://www.notion.so/coordinape/1-5-Allocations-Updates-21274b560fd74d1d9c9f99fda6dbe636) ||| [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5149%3A19110)

- Header that shows Epoch # and start and end dates
- Allocation table on left
- contribution/member detail view on right
- Allocation Filterbar on top
- Changes should be synced in realtime using [[optimistic updates](https://react-query.tanstack.com/guides/optimistic-updates#_top)](https://react-query.tanstack.com/guides/optimistic-updates#_top) with the “changes saved” and “saving changes” [[indicator in the Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5789%3A34209)](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5789%3A34209) (On Filterbar component)

### LINKED ISSUE #1162: Member Self Opt Out Fix
### **Problem**
On the allocation page, members are accidentally opting themselves out since it is the first option on the page. 

### **Solution**
Opt-In should be the first option on the allocation page and preselected for the user. 

### **Specification**
On the Allocation page, the options need to be flipped. It should appear as follows. 

**Example**
Should you receive GIVV distributions in the Apes Circle during this epoch?
(Selected) Opt-In
I want to be eligible to receive GIVV

Opt-Out
I am paid sufficiently via other channels.

### **Acceptance Criteria** 
Scenario: User wants to allocate
Given: The user is on the allocate page
Then: Opt-In should be selected

### **Stakeholders**
@spydermonkee

### PR DESCRIPTION
**Pull request by CryptoGraffe**
## Motivation and Context

We designed a new allocation/give workflow as part of 1.5 design work. This is it!

## Description

New GIVE page w/ table view, autosave, lots of room for future improvement. 

## Test and Deployment Plan

Run locally and try to go through allocation using the new UI. It's linked from the old allocate page in the allocation stepper if there is a current epoch. You should also try: 

* check out the page with no current epoch
* try various combinations of: 
** team selection disabled shouldn't matter, anyone can manage collaborators
** blocked from giving
** blocked from receiving
** opted out of giving
** no contributions, yes contributions
** no epoch statement, yes epoch statement
** 0 starting tokens, more than 100 starting tokens
* try weird timing stuff on the autosave
* toggling collaborators, paging through users

## Screenshots (if appropriate):

image

image

## Reviewers

@ivyquinzel @wingfeatherwave @topocount @zashton @levity @reeserj 

## Related Issue
Fixes #1162 
Fixes #928 
Fixes #926 
Fixes #927
Fixes #925 
Fixes #830 

## Out of scope and handling after:

More filtering and sorting
#929 
#1400 
#1401 
#1402

### CODE REVIEW

**Comment by CryptoGraffe** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1384** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1384" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1384?utm_source=stack-comment).

**Comment by wingfeatherwave** [comment]
Screen Shot 2022-09-27 at 3 14 13 PM

Distribute evenly didn't work.  Perhaps I have something not right in my local setup?  I can plus the give.

**Comment by CryptoGraffe** [comment]
This is because you haven’t marked anyone a collaborator yet - it only
distributes to collaborators. Maybe ivy has thoughts on this? I freestyled
the error message

**Review by wingfeatherwave — DISMISSED** [review]
Looking good.  Nice work!

**Comment by CryptoGraffe** [comment]
> Screen Shot 2022-09-27 at 3 14 13 PM
> 
> Distribute evenly didn't work. Perhaps I have something not right in my local setup? I can plus the give.

This behavior is now changed - distribute evenly distributes to all visible members.

**Comment by ivyquinzel** [comment]
Small UI detail, I notice people's names are cutting off that have a Y or G

**Review by crabsinger — COMMENTED** [review]
looks good - pretty dang clean PR!

**Review by crabsinger — COMMENTED** [review]
Found a bug - doesn't need to block this merging but should be fixed at some point:

* down arrow key on GIVE AMounts can make GIVE allocations negative
Screen Shot 2022-09-28 at 8 59 02 AM

**Comment by wingfeatherwave** [comment]
> Small UI detail, I notice people's names are cutting off that have a Y or G

Fixed, thanks Ivy!

**Comment by wingfeatherwave** [comment]
> Found a bug - doesn't need to block this merging but should be fixed at some point:
> 
> * down arrow key on GIVE AMounts can make GIVE allocations negative
> 
> Screen Shot 2022-09-28 at 8 59 02 AM

commited fix with `min="0"` html param

**Review by wingfeatherwave — APPROVED** [review]

**Comment by CryptoGraffe** [comment]
Weird I wonder why that skips the validation ! Good find. In probably need
to disable the scroll wheel thing on there too like in the other
application page

**Pull request merged**
