### PR TITLE
New nomination page

### PR DESCRIPTION
**Pull request by sshmm**
## Motivation and Context

Change Nomination modal to a page 

## Description
1- Created NewNominationPage
2- Removed NewNominationModal
3- Restyled NewNominationPage to match fima design
4- Added access rule so that users that can access will be able to access NewNominationPage 
5- Updated cypress test createNominee.cy.ts

## Test and Deployment Plan

1- login to a circle that you can nominate members to
2- go to Members Page and click Add Nominee
3- Enter Nominee Data and click save nominee and check the result
4- try to enter the same nominee data again and check the result

## Screenshots (if appropriate):

Success nomination
Screenshot from 2022-09-27 01-05-13

Failed Nomination
Screenshot from 2022-09-27 01-04-27

### CODE REVIEW

**Review by crabsinger — CHANGES_REQUESTED** [review]
@sshmm can we also update the link on Nominations from Overview/History page

image

to go to the right place.

**Comment by crabsinger** [comment]
Did we decide if we want to hide the Nominations table when it is empty? @ivyquinzel @sshmm  @ashmbanks

**Comment by wingfeatherwave** [comment]
> Did we decide if we want to hide the Nominations table when it is empty? @ivyquinzel @sshmm @ashmbanks

That is completed in this PR: https://github.com/coordinape/coordinape/pull/1412

**Comment by sshmm** [comment]
> Did we decide if we want to hide the Nominations table when it is empty? @ivyquinzel @sshmm @ashmbanks

I only made it to hide when nomination is disabled

**Comment by crabsinger** [comment]
> > Did we decide if we want to hide the Nominations table when it is empty? @ivyquinzel @sshmm @ashmbanks
> 
> I only made it to hide when nomination is disabled

@wingfeatherwave does this conflict with your recent changes that did in fact hide the table when no nominations are shown?

**Comment by sshmm** [comment]
> > > Did we decide if we want to hide the Nominations table when it is empty? @ivyquinzel @sshmm @ashmbanks
> > 
> > 
> > I only made it to hide when nomination is disabled
> 
> @wingfeatherwave does this conflict with your recent changes that did in fact hide the table when no nominations are shown?

I meant in the original implementation PR. This pr is not related to the table so it won't conflict with wing's

**Comment by sshmm** [comment]
> @sshmm can we also update the link on Nominations from Overview/History page
> 
> image
> 
> to go to the right place.

Done. Also I removed vouching link from circles link as this page is removed and its content moved to Members page
image

**Comment by wingfeatherwave** [comment]
@sshmm You've got some failing `yarn test` tests:
Screen Shot 2022-09-29 at 11 33 58 AM

**Comment by crabsinger** [comment]
@sshmm can you resolve the conflcits, rebase, and then i think this will be almost ready to merge! 🙏

**Comment by sshmm** [comment]
@wingfeatherwave  @crabsinger  I fixed the failed test and the merge conflict. I hope it gets merged because it seems the work in AdminPage is very active

**Review by crabsinger — APPROVED** [review]

**Pull request merged**
