### PR TITLE
Circle Integrations: database table, migrations and permissions

### PR DESCRIPTION
**Pull request by davidfant**
Short demo of what a v1 of a Dework integration that uses circle integrations could look like: https://www.loom.com/share/b1bf242508f647a983c5a8b4c7d7c74e

This PR adds a new table `circle_integrations`. Circle admins can insert and delete integrations. Everyone can read circle integrations.

In a future PR I will make the frontend use this table to create integrations and read/show epoch contributions using integrations

### CODE REVIEW

**Review by crabsinger — DISMISSED** [review]
This looks good to me. @topocount @META-DREAMER @zashton any thoughts you want to add?

**Review by zashton — CHANGES_REQUESTED** [review]
migrations looks good, but input wise i think it seems to be lacking validation , the admin is able to insert any circle_id (he might not even belong to that circle) /data/name/type.

**Comment by davidfant** [comment]
@zashton maybe I'm misunderstanding how the `insert_permissions` work, but wouldn't this (1) join the circle referenced by circle_id, and then join that circle's users? In that case all users fetched are connected to the circle, and if someone is an admin, they're authorized

**Comment by zashton** [comment]
> @zashton maybe I'm misunderstanding how the `insert_permissions` work, but wouldn't this (1) join the circle referenced by circle_id, and then join that circle's users? In that case all users fetched are connected to the circle, and if someone is an admin, they're authorized

yeap, you are correct . the permissions should cover that circle id part, so you'll just need to clone the same set of permissions for the other role `superadmin`. Would type and data require specific values for your integration to work ?

**Comment by davidfant** [comment]
> > @zashton maybe I'm misunderstanding how the `insert_permissions` work, but wouldn't this (1) join the circle referenced by circle_id, and then join that circle's users? In that case all users fetched are connected to the circle, and if someone is an admin, they're authorized
> 
> yeap, you are correct . the permissions should cover that circle id part, so you'll just need to clone the same set of permissions for the other role `superadmin`. Would `type` and `data` require specific values for your integration to work ?

Added permissions for the `superadmin role`!

For type and data: type would be e.g. "dework" or "github" and data is a JSON blob that contains whatever the integration needs to fetch tasks. For dework, that would be "{ organizationId: string }" which then is used to fetch Dework tasks. For Github it might be an oauth access/refresh token

**Comment by zashton** [comment]
> > > @zashton maybe I'm misunderstanding how the `insert_permissions` work, but wouldn't this (1) join the circle referenced by circle_id, and then join that circle's users? In that case all users fetched are connected to the circle, and if someone is an admin, they're authorized
> > 
> > 
> > yeap, you are correct . the permissions should cover that circle id part, so you'll just need to clone the same set of permissions for the other role `superadmin`. Would `type` and `data` require specific values for your integration to work ?
> 
> @zashton I added permissions for the `superadmin role`!
> 
> For type and data: type would be e.g. "dework" or "github" and data is a JSON blob that contains whatever the integration needs to fetch tasks. For dework, that would be "{ organizationId: string }" which then is used to fetch Dework tasks. For Github it might be an oauth access/refresh token

Thanks, do commit and i'll review

**Comment by zashton** [comment]
> @zashton forgot to push... Check now!

Do you need to put an unique constraint ?  i could insert multiple rows of the same circle id. I assume your FE integration will ignore the whole row of data if `type` and `data` is of the wrong format.

**Comment by davidfant** [comment]
@zashton 
Unique constraint: I left it open for now. For example, if we'd want project-specific Dework connections and you wanted to add 2 boards, it might be easiest of that would be 2 integrations. Lmk if you disagree or think another path forward would make more sense.

Integrations with unknown type/data: yes they'll be ignored. That way we can keep adding integrations over time and the client will simply pick up the integrations it knows about/supports

**Comment by zashton** [comment]
> @zashton Unique constraint: I left it open for now. For example, if we'd want project-specific Dework connections and you wanted to add 2 boards, it might be easiest of that would be 2 integrations. Lmk if you disagree or think another path forward would make more sense.
> 
> Integrations with unknown type/data: yes they'll be ignored. That way we can keep adding integrations over time and the client will simply pick up the integrations it knows about/supports

yeap make sense to me if a circle can have multiple boards ! looks good to me 👍

**Review by zashton — APPROVED** [review]

**Pull request merged**
