### PR TITLE
Rename schema users to members

### PR DESCRIPTION
**Pull request by zashton**
## Motivation and Context

Renaming of the `users` table and all its relationships to `members` for better clarity 

## Description

- [x] Migrations to rename all existing instances of users in the DB to members
- [x] Update the metadata to reflect the changes caused by the migrations
- [x] Modify all App references of `users` to `members`
- [ ] Merge main branch into PR and resolve all the conflicts caused by this change.

### CODE REVIEW

**Comment by zashton** [comment]
@crabsinger is there an easy way to resolve merge conflicts for the zeus generated files or we have to do it manually ?

**Comment by crabsinger** [comment]
> @crabsinger is there an easy way to resolve merge conflicts for the zeus generated files or we have to do it manually ?

@zashton sorry I missed this - usually I can just delete the conflicts and ran `yarn generate` to regenerate them. But if theyre so broken the app won't start, it might be a bit harder. But usually trying to get `yarn generate` to re-run is the best way.

How's this coming along?

**Comment by zashton** [comment]
> > @crabsinger is there an easy way to resolve merge conflicts for the zeus generated files or we have to do it manually ?
> 
> @zashton sorry I missed this - usually I can just delete the conflicts and ran `yarn generate` to regenerate them. But if theyre so broken the app won't start, it might be a bit harder. But usually trying to get `yarn generate` to re-run is the best way.
> 
> How's this coming along?

had issues trying to resolve the conflicts in the zeus generated files the previous time i tried, I have moved on to cosouls pod work for now will come back to this again later.

**Comment by levity** [comment]
Will revisit this in the future, in smaller pieces

**Pull request closed without merging**
