### PR TITLE
fixes #634 by migrating FE to use vouch mutation

### LINKED ISSUE #634: Integrate Hasura Vouching into FE
## Summary:
Integrate Hasura Vouching into FE.

### Details
This task is to integrate the frontend of `Vouching` to Hasura.
https://app.coordinape.com/vouching

**Screenshot of Page**
image

**Logic:**
-

**Related Backend Issue:**
#519

### PR DESCRIPTION
**Pull request by CryptoGraffe**
Fixes #634 by integrating mutation in FE. 

To test:

1. db-seed-fresh
2. navigate to Conn -Friese Health circle
3. Vouch for Malinda

... Nothing in the UI changes (see bug I submitted #687 ) but you can tell it worked because you can't vouch again. I verified this workflow behaves the same with and without this ticket implemented.

### CODE REVIEW

**Review by zashton — APPROVED** [review]
tested and working

**Review by levity — DISMISSED** [review]

**Review by zashton — CHANGES_REQUESTED** [review]
enable the event triggers in `eventManager`
`vouchDiscord`,`vouchTelegram`
before you merge

**Comment by CryptoGraffe** [comment]
> enable the event triggers in `eventManager` `vouchDiscord`,`vouchTelegram` before you merge

Ok these are fixed and this is ready for re-review.

**Review by zashton — APPROVED** [review]

**Comment by CryptoGraffe** [comment]
@zashton ready for review yet again after conflict resolution

**Review by zashton — APPROVED** [review]
lgtm

**Pull request merged**
