### PR TITLE
investigating the hasura-preview CI workflow

### PR DESCRIPTION
**Pull request by wawhal**
Looking into the Hasura Cloud CI workflow. Please feel free to ignore this PR

### CODE REVIEW

**Comment by wawhal** [comment]
@crabsinger another approval on the deployment please :pray: 
The first one failed due to [an unrelated error](https://github.com/coordinape/coordinape/runs/5633827503?check_suite_focus=true) with adding an env to Vercel.

**Comment by crabsinger** [comment]
@wawhal done.

**Comment by wawhal** [comment]
Looks like the `VERCEL_TOKEN` secret is empty in the workflow. That's causing the setting and removing vercel env step to fail.

**Comment by crabsinger** [comment]
> Looks like the `VERCEL_TOKEN` secret is empty in the workflow. That's causing the setting and removing vercel env step to fail.

@wawhal yeah, we don't allow secrets to be passed to Github Actions that run on forks. I've copied this branch to not be a fork here: https://github.com/coordinape/coordinape/pull/664 and it built successfully.

**Pull request closed without merging**
