### PR TITLE
cleanup circle admin page

### PR DESCRIPTION
**Pull request by levity**
## What

Remove cruft from the circle admin page

### CODE REVIEW

**Review by crabsinger — APPROVED** [review]

**Comment by levity** [comment]
@levity queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2091).

**Comment by levity** [comment]
[Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2091) rebased this pull request as part of a merge.

**Comment by levity** [comment]
@levity queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/2091).

**Comment by crabsinger** [comment]
> @levity <https://github.com/levity> queued this pull request to merge with
 Graphite <https://app.graphite.dev/github/pr/coordinape/coordinape/2091>.

Does graphite have a merge queue that works well?

**Comment by levity** [comment]
@crabsinger 
> Does graphite have a merge queue that works well?

so far so good. i went to https://app.graphite.dev/github/pr/coordinape/coordinape/2091/cleanup-circle-admin-page and just clicked the Merge button to kick it all off. the only wrinkle was that the 1st PR in this stack of 5 wasn't included (i think because some check failed), so i merged that one individually first.

**Pull request merged**
