### PR TITLE
feat: Add `Divider` story

### PR DESCRIPTION
**Pull request by karelianpie**
## Motivation and Context

Add all our current components into Storybook via stories.

## Description

* Implement a basic story for the `Divider` component.

## Test and Deployment Plan

Ran storybook locally and observed the story, refer to the screenshot below:

## Screenshots (if appropriate):

Screenshot 2022-11-06 at 10 35 05

## Reviewers

@crabsinger 

## Related Issue

https://github.com/coordinape/coordinape/issues/1570

### CODE REVIEW

**Review by levity — CHANGES_REQUESTED** [review]
This appears to be a duplicate of `HR`. We should remove one (cc @wingfeatherwave)

**Comment by levity** [comment]
Maybe you can remove the Divider.stories change from this PR so we can merge the fixes for main.js

**Comment by karelianpie** [comment]
> Maybe you can remove the Divider.stories change from this PR so we can merge the fixes for main.js

Easiest would be to merge this and then have a PR to merge `Divider` and `HR`, happy to do the follow up refactor if we decide to just use one `hr`

**Comment by levity** [comment]
> > Maybe you can remove the Divider.stories change from this PR so we can merge the fixes for main.js
> 
> Easiest would be to merge this and then have a PR to merge `Divider` and `HR`, happy to do the follow up refactor if we decide to just use one `hr`

Let's not merge code only to remove it soon after. I see that the `main.js` changes are also in another story PR, so I'll just close this one.

**Comment by karelianpie** [comment]
> > Easiest would be to merge this and then have a PR to merge `Divider` and `HR`, happy to do the follow up refactor if we decide to just use one `hr`
> 
> Let's not merge code only to remove it soon after. I see that the `main.js` changes are also in another story PR, so I'll just close this one.

I think "soon" is a bit relative, it might take a while, I think that would be preferable than letting the PRs sit in review

**Pull request closed without merging**
