### PR TITLE
Implement restore user hasura action

### PR DESCRIPTION
**Pull request by amrro**
Part of #558
related: #701.
____
Test Plan:
1. Pick a previously deleted user to delete.
2. If there is no deleted user, follow #701.
2. run the following mutation:
```graphql
mutation {
  restoreUser(payload: {circle_id: <id>, address: <address>}) {
      success
  }
}
```

4. query the same user and make sure that `deleted_at` has become null:
```graphql
{
  users(where: {id: {_eq: <id>}}) {
    id
    deleted_at
  }
}
```

### CODE REVIEW

**Comment by amrro** [comment]
Closing this since @topocount implemented this in #708.

**Comment by zashton** [comment]
> Part of #558 related: #701.
> 
> Test Plan:
> 
> 1. Pick a previously deleted user to delete.
> 2. If there is no deleted user, follow [Implement deleteUser hasura action #701](https://github.com/coordinape/coordinape/pull/701).
> 3. run the following mutation:
> 
> ```graphql
> mutation {
>   restoreUser(payload: {circle_id: <id>, address: <address>}) {
>       success
>   }
> }
> ```
> 
> 4. query the same user and make sure that `deleted_at` has become null:
> 
> ```graphql
> {
>   users(where: {id: {_eq: <id>}}) {
>     id
>     deleted_at
>   }
> }
> ```

Hi @amrro just saw this PR, there actually is user demand for a bulk creation version of what topocount did. Would you interested in working on that ? I could also scope that out so your work in this PR doesn't go to waste

**Comment by amrro** [comment]
@zashton yes, I'm interested. 
Would you open an issue for that and assign it to me?
Thanks for asking.

**Comment by zashton** [comment]
> @zashton yes, I'm interested. Would you open an issue for that and assign it to me? Thanks for asking.

just created it #775

**Pull request closed without merging**
