### PR TITLE
add tooltip to coordinape user under admin user list

### PR DESCRIPTION
**Pull request by j-yw**
completes #557 

tooltip added to coordinape user with the correct link.

Screen Shot 2022-04-01 at 3 11 55 PM

### CODE REVIEW

**Comment by crabsinger** [comment]
@j-yw same here, can we separate out the `stream` addition into a separate PR to discuss. that will unblock adn allow these PRs to move forwards.

**Comment by j-yw** [comment]
> @j-yw same here, can we separate out the `stream` addition into a separate PR to discuss. that will unblock adn allow these PRs to move forwards.

My apologies that this was overlooked. fixing all of it today.

**Review by levity — CHANGES_REQUESTED** [review]
Tooltip header text needs to be bold, and link should open in a new tab.

**Comment by j-yw** [comment]
> Tooltip header text needs to be bold, and link should open in a new tab.

done!

**Comment by crabsinger** [comment]
@j-yw can you add a screenshot or video of this change so its easier to review.

**Comment by j-yw** [comment]
> 

good call, added a screen capture for context.

**Comment by crabsinger** [comment]
Hi @j-yw if possible, if you can embed the video or screenshot directly in the PR description, so you can view it without going to another page, that is ideal. That way, when someone goes to the PR description, they can instantly see a visual representation of what is changing without having to visit any other pages.

**Review by crabsinger — APPROVED** [review]

**Review by crabsinger — CHANGES_REQUESTED** [review]
@j-yw the design spec is this:
Screen Shot 2022-03-31 at 4 29 55 PM

this is the current preview version I see:
Screen Shot 2022-03-31 at 4 30 01 PM


Please make the title bold as Lawris requested

**Comment by j-yw** [comment]
It is bold on my system, I'm using a b tag. Could it be your system not rendering correctly, I noticed a slight color difference between the title and the text from your screen shots.

I'll write some custom css.

**Comment by j-yw** [comment]
> @j-yw the design spec is this: Screen Shot 2022-03-31 at 4 29 55 PM
> 
> this is the current preview version I see: Screen Shot 2022-03-31 at 4 30 01 PM
> 
> Please make the title bold as Lawris requested
Screen Shot 2022-04-01 at 3 11 55 PM



added some CSS to meet the design spec

**Comment by levity** [comment]
Merged in #746

**Pull request closed without merging**
