### PR TITLE
Implement deleteUser hasura action

### LINKED ISSUE #543: Migrate Delete User v2/{circle_id}/admin/{address}
## Summary:
Migrate Delete User Laravel API Endpoint functionality to Hasura.

### Details
This task is to migrate the functionality of `<DELETE v2/{circle_id}/admin/{address}>` to Hasura.

In Laravel, this endpoint has the following functionality.

**Middleware:** Hasura circle admin + event secret middleware

**Additional Validations besides basic inputs:**
- admin and deleted user in the same circle
- check if address exists in the circle

**Logic:**

Set user's `deleted_at` col to current timestamp. Purge all `pending_gifts` rows with token value received/sent by the user. Refund the `token` value of each into the sender's `give_token_remaining`. Next, deduct the `token` value of each from the recipient's `give_token_received`. Delete all records of `teammates` that has `user_id` or `team_mate_id` associated with it. Finally, soft delete the user by setting the current timestamp at `deleted_at`. Also set its `give_token_received` to 0 , `give_token_remaining` to its `starting_tokens` value . 

**DB Tables:**
`users`, `pending_token_gifts`, `teammates`

#### Notes:
theres a possibility we could change the `address` input to `user_id`, shall leave it to the person implementing.

### PR DESCRIPTION
**Pull request by topocount**
closes #543

test plan:

1. start an epoch
2. give tokens to others in the the circle
3. execute
```gql
mutation deleteMe {
  deleteUser(payload: {circle_id: <your circle id>, address: "<your address>" }) {
    success
  }
}
```

4. verify
  a. that your user has a deleted_at timestamp
  b. your user's give_token values have been reset
  c. the users you gave to have had their token values reset
  d. the pending_token_gifts entries created by your user have been
  deleted.
  e. all of your teammate entries have been deleted

5. optionally test receiving gifts from others and deleting your user.

### CODE REVIEW

**Review by zashton — APPROVED** [review]
went through test plan with no issues

**Comment by crabsinger** [comment]
@CryptoGraffe 

did we miss a criteria under the verify step of

```
verify
a. that your user has a deleted_at timestamp
b. your user's give_token values have been reset
c. the users you gave to have had their token values reset
d. the pending_token_gifts entries created by your user have been
deleted.
e. all of your teammate entries have been deleted
```

f: any give sent to deleted user is reset (delete the pending_token_gifts where recipient_id is deleted user))? Or is that happening somehow already?

**Comment by CryptoGraffe** [comment]
I believe this is supposed to happen in event triggers

**Comment by CryptoGraffe** [comment]
Topo would know better

**Comment by crabsinger** [comment]
cc @topocount

**Comment by zashton** [comment]
> cc @topocount

its happening in this event trigger when the teammate gets removed in the deleteUser action handler.
I think currently theres an edge case when teammates setting is disabled in the circle and the teammate removal doesn't happen hence the refund doesn't get trigger

**Pull request merged**
