### PR TITLE
story: Panel with Select

### PR DESCRIPTION
**Pull request by karelianpie**
## Motivation and Context

The `Panel` component is lacking documentation when it comes to its usage, for example https://discord.com/channels/845400066532704256/898299792575299654/1025452274824253591

## Description

Add a story for the `Panel` component

## Test and Deployment Plan

Ran storybook and saw the `Panel` story working correctly with a `Select` and `TextArea` components

## Screenshots (if appropriate):

Screen Shot 2022-10-03 at 10 46 40 am

## Reviewers

@wingfeatherwave 

## Related Issue

Closes https://github.com/coordinape/coordinape/issues/1441

### CODE REVIEW

**Comment by crabsinger** [comment]
Thanks for adding a story for this. We've thought about (but not yet setup I don't think) a deployment of our Storybook so people can play around with our components on a hosted version as well. And add even more components to it. So thanks for adding this one!

**Comment by karelianpie** [comment]
> Thanks for adding a story for this. We've thought about (but not yet setup I don't think) a deployment of our Storybook so people can play around with our components on a hosted version as well. And add even more components to it. So thanks for adding this one!

I would be happy to add stories for other components, would that be considered high(ish) importance? I just added this one since Wing mentioned that this `Panel` should be better documented.

Let me know if I should start writing more stories or if there's something more important, I am looking at the Zodiac module for the Gnosis Safe integration at the moment (https://github.com/coordinape/coordinape/issues/1255) but I'm lacking a lot of context, so going through documentation and so on at the minute

**Review by wingfeatherwave — APPROVED** [review]

**Comment by crabsinger** [comment]
@karelianpie I think it would be great to find Storybook deployment solution as well, on gh-pages or someplace else so we can easily view Storybook not only in local, then yes, adding more examples to it would be pretty valuable, if you want to work on this more.

**Comment by karelianpie** [comment]
> @karelianpie I think it would be great to find Storybook deployment solution as well, on gh-pages or someplace else so we can easily view Storybook not only in local, then yes, adding more examples to it would be pretty valuable, if you want to work on this more.

Sounds good, created a PR https://github.com/coordinape/coordinape/pull/1454 -- we only need now to create an account on [Chromatic](https://www.chromatic.com/) and set the env vars for the CI to publish it automatically

Once that's merged I can start adding a few more stories

**Pull request merged**
