### PR TITLE
Fix responsive header

### PR DESCRIPTION
**Pull request by levity**
See #245 for context

### CODE REVIEW

**Comment by levity** [comment]
> This is NOT ready for release @levity

yep I understand :) I just created it so that we can follow along with progress with a Vercel preview app

**Comment by almithani** [comment]
This COULD be merged, the thing that's missing is a burger icon for the mobile header menu.  I could make one, but I understand someone is working on the design, so I didn't think I should step on their toes.  Essentially, when you're on mobile, you can click the logo to toggle the menu.  I default left the menu visible, because without a burger icon it's not clear the menu exists (see line 170 of MainHeader.tsx).

It fixes two issues from here: https://github.com/coordinape/coordinape/issues/245

- Top menu items (allocate, map, admin) force user profile icon misalignment  (RECO: create hamburger menu to replace top menu)
    - this is Reese's issue 
- Epoch table dates overlap the table header/footer (RECO: ensure row CSS handles additional content lines)
    - this is @exrhizo's issue


Here's what the menu looks like on mobile now:
Screen Shot 2021-11-07 at 7 30 08 PM


Here's a page where it overlaps content 
Screen Shot 2021-11-07 at 7 30 26 PM

Here's the epoch table:
Screen Shot 2021-11-07 at 7 29 55 PM

**Comment by exrhizo** [comment]
I'll get this to a point were we can merge it, I am going to need to change somethings in the header for the login update, so I can gather this up for that as well.

**Comment by exrhizo** [comment]
I did some small changes to get this mergable:
https://github.com/coordinape/coordinape/pull/267

**Comment by exrhizo** [comment]
Merged as https://github.com/coordinape/coordinape/pull/267

**Pull request closed without merging**
