### PR TITLE
add tooltip to teammate view in allocationPage

### LINKED ISSUE #560: "Coordinape In Your Circle": Tooltip and link in Teammates view
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
- Add tooltip link ("Why is Coordinape in my circle?") and tooltip list in the Teammates view. 
- Link on tooltip ("Let us know what you think")) goes here: https://coordinape.notion.site/Why-is-Coordinape-in-my-Circle-fd17133a82ef4cbf84d4738311fb557a

Design: 
https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2731%3A10174

### PR DESCRIPTION
**Pull request by j-yw**
fixes #560

https://capture.dropbox.com/oTj4Yd7xqkoMDDYh?intro=1

### CODE REVIEW

**Review by crabsinger — CHANGES_REQUESTED** [review]
@j-yw 

seems there is an icon that sits above the "Why is COordinape in my circle?" text on the Select Team page, that isn't as the Figma describes:

In this screenshot I circled the icon and the extra space above it.

Screen Shot 2022-03-24 at 4 19 28 PM

**Comment by j-yw** [comment]
> 

Sorry i misunderstood before and thought we should kept the tooltip icon as it's the default behavior from the ApeToolTip component.

nonetheless I wrote something rather custom to meet the design

**Comment by crabsinger** [comment]
@j-yw Is this fully done, or not?
can you update the description of this PR to note the status of this, and remove any TODOs from the description if completed.
please add a screenshot or video of the change to PRs as well. that will help us review and merge your contributions.

**Comment by j-yw** [comment]
> 

It is finished and I've added a screen capture to demo.

**Review by crabsinger — APPROVED** [review]

**Comment by crabsinger** [comment]
@j-yw you can re-open this in a new PR to address the bug I found: https://github.com/coordinape/coordinape/pull/728

**Pull request merged**
