### PR TITLE
Eth Denver competition announcement

### PR DESCRIPTION
**Pull request by sshmm**
## What
Create Eth denver competition wizard step
https://www.notion.so/coordinape/2024-02-14-DEV-2b4813306347424ca825ef5fac9beaee#05f53964730c459f840afd6281a6dbef

## Testing
1- in helperAccounts.ts make ETH_DENVER_INVITER_ADDRESS = 'your-address' your account should have a colinks account with own link and cosoul
2- get an invite code from the first address and use it for a new account
3- the wizard step should appear after buying your own links step for the second account

## How
1- an action to get the inviter id and compare it with eth denver 2024 inviter id
2- add a wizard step to be triggered for these users

## Screenshot
Screenshot from 2024-02-20 16-29-05

### CODE REVIEW

**Comment by wingfeatherwave** [comment]
Screenshot 2024-02-20 at 4 24 44 PM
I'm adding this hint banner in the app

**Comment by wingfeatherwave** [comment]
@sshmm Can you confirm that each new user receives 10 invite codes?

**Comment by sshmm** [comment]
> @sshmm Can you confirm that each new user receives 10 invite codes?

they get 5 normally unless they are early access users

**Review by wingfeatherwave — APPROVED** [review]
nice work

**Pull request merged**
