### PR TITLE
Allow Editing Current Epoch

### PR DESCRIPTION
**Pull request by sshmm**
## Motivation and Context

implements #1138 - Fixes an issue regarding the Editing Form where the form remains open if the user switched to another circle.

## Description
1- Add Edit button to current Epoch if the user is Admin.
2- Disable editing start date and start time in EpochForm for current Epoch.
3- The validation is between current epoch and future epochs if not empty
3- Bypass comparing between start date and current time for current epoch.

## Test and Deployment Plan
1- Tested editing current epoch with and without Available upcoming epochs.
2- Retested adding new epochs and editing next epochs.

## Screenshots (if appropriate):
Admin
image
image

Regular user
image

### CODE REVIEW

**Review by crabsinger — APPROVED** [review]
lgtm

**Comment by CryptoGraffe** [comment]
If you choose repeat and then get into an error state, choosing no-repeat and entering a valid day does not clear error state 
image

Also clicking the labels for the radio buttons selects no-repeat instead of the associated radio button. 

Both of these could be handled in separate tickets since this is somewhat urgent to get deployed.

**Comment by sshmm** [comment]
> If you choose repeat and then get into an error state, choosing no-repeat and entering a valid day does not clear error state image
> 
> Also clicking the labels for the radio buttons selects no-repeat instead of the associated radio button.
> 
> Both of these could be handled in separate tickets since this is somewhat urgent to get deployed.

It validates on submit not on change and it will clear and submit or show new errors on clicking save

**Comment by CryptoGraffe** [comment]
@sshmm ok this is ok for now but kinda weird experience. maybe would be best to clear error on edit if we can't do client side validation. not critical for this ticket

**Comment by sshmm** [comment]
> @sshmm ok this is ok for now but kinda weird experience. maybe would be best to clear error on edit if we can't do client side validation. not critical for this ticket

You are right but the validation is done on the ient but you have to click submit first.
I can work on this tomorrow (today for me UTC+2) to make the experience better but may be in another issue to merge this one first

**Comment by levity** [comment]
Thanks for the timely support on this, everyone!

**Comment by spydermonkee** [comment]
Yes, thank you @sshmm and @CryptoGraffe (and @levity)!

**Pull request merged**
