### PR TITLE
Edit Epoch Description Inline

### PR DESCRIPTION
**Pull request by crabsinger**
Resolves https://github.com/coordinape/coordinape/issues/1904

Move epoch description editing from the main form, into a inline experience.

* Change the epoch description field to be limited between 1 and 100 chars
* Enable graphql API updates for circle admins to modify the epoch description field
  - constraints on updates of epoch description:
    - must be circle admin, must be undeleted
    - epoch must be NOT ended
* Remove description from Epoch form
* Add edit icon and inline editing expereience for epoch descriptions for "current epochs"

Testing:
- API endpoint is secured for non-admin users
- Inline expereience works as expected
- Errors are handled and shown via toast bar

### CODE REVIEW

**Comment by crabsinger** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1771** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1771" target="_blank">Graphite</a> 
    * **PR #1772** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1772" target="_blank">Graphite</a> 
      * **PR #1773** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1773" target="_blank">Graphite</a> 
        * **PR #1829** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1829" target="_blank">Graphite</a> 
          * **PR #1832** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1832" target="_blank">Graphite</a> 
            * **PR #1774** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1774" target="_blank">Graphite</a> 
              * **PR #1903** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1903" target="_blank">Graphite</a>  👈
            * **PR #1866** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1866" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1903?utm_source=stack-comment).

**Comment by crabsinger** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1771** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1771" target="_blank">Graphite</a> 
    * **PR #1772** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1772" target="_blank">Graphite</a> 
      * **PR #1773** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1773" target="_blank">Graphite</a> 
        * **PR #1829** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1829" target="_blank">Graphite</a> 
          * **PR #1832** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1832" target="_blank">Graphite</a> 
            * **PR #1774** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1774" target="_blank">Graphite</a> 
              * **PR #1903** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1903" target="_blank">Graphite</a>  👈
            * **PR #1866** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1866" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1903?utm_source=stack-comment).

**Review by topocount — COMMENTED** [review]
I need to test this out, but the code looks good. Glad to see the removals from the epoch form. Definitely see this api and permissions scope as the cleanest, easiest thing to maintain, out of all our options.

**Review by topocount — APPROVED** [review]
Tested it, and really appreciate the cleanup and removal in the EpochForm! Nice work

**Pull request merged**
