### PR TITLE
what's your name modal in side nav

### PR DESCRIPTION
**Pull request by CryptoGraffe**
## Motivation and Context

add the what's your name modal to new sidenav. For the legacy theme it's embedded in the MainHeader so it needed to be moved to the new NavProfile

### CODE REVIEW

**Comment by CryptoGraffe** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1811** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1811" target="_blank">Graphite</a> 
    * **PR #1835** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1835" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1835?utm_source=stack-comment).

**Comment by crabsinger** [comment]
@CryptoGraffe 
Pushed a fix for the issue you were encountering - styles are wonk still:

Screenshot 2023-01-20 at 12 00 48 PM

**Comment by CryptoGraffe** [comment]
The style issues crab was seeing are gone now, maybe due to upstream changes. This should be squashed on merge.

**Review by levity — APPROVED** [review]
This seems fine. I notice though that the `InvalidateSideNav` pattern is a bit more encapsulated, since if it was ever needed, you could invalidate multiple queries or do other work in that method without having to change callers. 🤷

**Comment by CryptoGraffe** [comment]
Thanks @levity for the review. the invalidate func was causing some weird circular dep thing that was causing whole site to white screen. Might try some version of that later. There are more changes in here that need review now.

**Review by levity — APPROVED** [review]

**Pull request merged**
