### PR TITLE
Fix: Username not wrapping on Allocation ProfileCard, ProfilePage Name and Nominee Card

### PR DESCRIPTION
**Pull request by tsejerome**
Resolves Issue #595

### CODE REVIEW

**Review by levity — CHANGES_REQUESTED** [review]
this looks good, but I don't think `gridColumn` should have been added--it makes sense in ProfileCard because there's a grid container, but not in the other two

**Comment by tsejerome** [comment]
@levity interesting, are you referring to "make sense" as a coding best practices or "make sense" as working or not 🤔

If you are concerned about working or not, I had attached some screenshots in the issue, in terms of UI it should be working for both brave browser and Firefox (tested on my Mac). Then the PR cud be closed.

If you are referring to best practices, I can add display: grid for their respective containers.

**Comment by levity** [comment]
It seems to not have a purpose? i.e. the code would work fine without it? Maybe I'm mistaken.

**Comment by tsejerome** [comment]
Oh I misunderstood what you meant, you are right let me remove it.

**Review by levity — APPROVED** [review]

**Comment by levity** [comment]
congrats on your first merged PR @tsejerome! 🎉

**Pull request merged**
