### PR TITLE
MVP integration with Spirals: Green ETH as Simple CoVault Token

### PR DESCRIPTION
**Pull request by a2ronprice**
Gives choice for Green ETH as Simple Token in CoVault creation.

## Motivation and Context

- This change starts the collaboration of Coordinape and Spirals.
- Green ETH is the receipt from liquid staking ETH where the generated yield in sent towards climate projects.
- Green ETH is always 1:1 redeemable for the underlying staked ETH.

## Description

- Added Green ETH as asset
- Created new list called "YearnAsset" to differentiate Yearn vault token options from simple options.
- Created new function getAvailableYearnTokens() mimicking getAvailableTokens() using YearnAsset for token list.
- Updated deploymentInfo.json to include Green ETH token address on chains 1,5.

## Test and Deployment Plan

- Choose "Green ETH" as token for creating new CoVault. 
- When transaction appears in wallet, verify the simpleToken address is 0x06a0CCFb89E9B2814afCA6637C22ed83909739Ee on Etherscan.

## Screenshots (if appropriate):

image

### CODE REVIEW

**Review by levity — COMMENTED** [review]
Looks pretty good so far. There's a conflict only because I just merged #1734 which also changes deploymentInfo.json, but resolving the conflict is straightforward.

FYI, for future PRs, if you turned on "[Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)", anyone on our team could resolve the conflict.

**Comment by crabsinger** [comment]
@a2ronprice one design thing I'm noticing - at this size, the Green Eth logo looks very much like the default Eth logo - and I worry that some may confuse them even if the text is different. This is your standard Green Eth logo? Is there another version with more visual difference?

**Review by crabsinger — CHANGES_REQUESTED** [review]
want to make sure some details are finalized before merging.

**Comment by crabsinger** [comment]
closing for now

**Pull request closed without merging**
