### PR TITLE
Migrate FE getProfile to use Hasura

### LINKED ISSUE #759: Migrate getProfile query to graphql
## Summary:
Migrate getProfile query to graphql

### PR DESCRIPTION
**Pull request by CryptoGraffe**
Fixes #759 

I'm going to merge this into staging and deploy there for testing.

To test:

1. visit other users profile pages and make sure they look good!

### CODE REVIEW

**Review by META-DREAMER — DISMISSED** [review]
Looks good to me, tested the live app

**Comment by levity** [comment]
"My Circles" and "Recent Epoch Activity" seem to be broken on other users' profiles. Compare [production](https://app.coordinape.com/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) and [staging](https://coordinape-git-staging-coordinape.vercel.app/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) for the same user

**Comment by levity** [comment]
> "My Circles" and "Recent Epoch Activity" seem to be broken on other users' profiles. Compare [production](https://app.coordinape.com/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) and [staging](https://coordinape-git-staging-coordinape.vercel.app/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) for the same user

though FWIW it's not clear to me that these are high-value features so it wouldn't be the end of the world IMO if they were just temporarily removed

**Comment by CryptoGraffe** [comment]
> "My Circles" and "Recent Epoch Activity" seem to be broken on other users' profiles. Compare [production](https://app.coordinape.com/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) and [staging](https://coordinape-git-staging-coordinape.vercel.app/profile/0x756bd520e6d52ba027e7a1b3cd59f79ab61dfc34) for the same user

@levity I sorted this out now, if you wanted to re-test and approve. Thanks!

**Review by levity — APPROVED** [review]

**Pull request merged**
