### PR TITLE
Feature/ape 220 tooltips

### PR DESCRIPTION
**Pull request by jsur**
- Added tooltips to `AdminCircleModal`
- Added hover style to `ApeInfoTooltip`

Style `tooltipLink` is the same as in `ProfileCard`, should this be a common style somewhere?

### CODE REVIEW

**Comment by crabsinger** [comment]
@jsur nice work on this. Looks good to me. Do these models work ok on mobile/touch screen?

**Comment by crabsinger** [comment]
@f1lander 
> Style tooltipLink is the same as in ProfileCard, should this be a common style somewhere?
Thoughts on this? Can we make a common style somewhere?

**Comment by jsur** [comment]
> @jsur nice work on this. Looks good to me. Do these models work ok on mobile/touch screen?

Huh, I didn't try, good point - been working with corporate desktop apps for too long I guess. I'll try that out as well.

**Comment by levity** [comment]
in https://github.com/coordinape/coordinape/pull/306, @f1lander has set up an ApeInfoTooltip that you can tap to open on mobile, and I just suggested that he add that behavior to the component itself... seems relevant :)

**Comment by jsur** [comment]
The material-ui tooltip used here opens on a touch screen after 700ms, it can be modified with `enterTouchDelay`: https://mui.com/api/tooltip/#props

Looks like the design in general doesn't work with mobile yet:

Screenshot 2021-11-23 at 23 05 37

**Comment by crabsinger** [comment]
@coordinape/designers FYI

**Comment by exrhizo** [comment]
Awesome - Thank you :)
I could imagine we roll this into ApeInfoToolip at some point.

**Comment by jsur** [comment]
I rebased master to resolve a conflict and had to force push to get my changes in - if all is good this can be merged!

**Comment by exrhizo** [comment]
To save time, I copied the branch, rebased it on master and merged:
https://github.com/coordinape/coordinape/pull/331

**Pull request closed without merging**
